import { ReactNode } from "react";
import "./globals.css";

export const metadata = {
  title: "Open Table Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* Navbar here */}
        {children}
        </body>
    </html>
  );
}
